---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canhvpdemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: canhvpdemo
  template:
    metadata:
      labels:
        app: canhvpdemo
    spec:
      containers:
      - name: canhvpdemo
        image: registrydemodevsecops.azurecr.io/canhvp:latest
        ports:
        - containerPort: 3000   # Use port 3000

---
apiVersion: v1
kind: Service
metadata:
  name: canhvpdemo-service
spec:
  selector:
    app: canhvpdemo
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 3000
  type: LoadBalancer

